services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
    volumes:
      - ./api-gateway:/app
    networks:
      - local_network

 # Write Kweet Service
  write-kweet:
    build:
      context: ./write
    environment:
      POSTGRES_DB_KWEET: ${POSTGRES_DB_KWEET}
      POSTGRES_USER_KWEET: ${POSTGRES_USER_KWEET}
      POSTGRES_PASSWORD_KWEET: ${POSTGRES_PASSWORD_KWEET}
    depends_on:
      postgres-kweets:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - local_network
  
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - local_network

  postgres-kweets:
    image: postgres:16.2
    volumes:
      - postgres_kweets_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_KWEET}
      POSTGRES_USER: ${POSTGRES_USER_KWEET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_KWEET}
      POSTGRES_INITDB_ARGS: "--wal-level=logical --max-wal-senders=1 --max-replication-slots=1"
    networks:
      - local_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_KWEET} -d ${POSTGRES_DB_KWEET}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    environment:
      KC_HOSTNAME: localhost:8081
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8081:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - local_network

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"   # Mailpit web interface
      - "1025:1025"   # SMTP
    environment:
      - MAILPIT_API=1
    networks:
      - local_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # Disable security features
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Limits memory usage
    ports:
      - "9200:9200"  # HTTP interface
      - "9300:9300"  # Transport protocol
    networks:
      - local_network
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  debezium:
    image: debezium/connect:2.3
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
    ports:
      - "8083:8083" # Debezium REST API
    depends_on:
      - kafka
      - zookeeper
    networks:
      - local_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - local_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - local_network

volumes:
  postgres_data:
    driver: local
  postgres_kweets_data:
    driver: local
  elastic_data:
    driver: local

networks:
  local_network:
    driver: bridge
