services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - keycloak

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
      ports:
        - "8081:8080"  # Keycloak's internal port exposed on 8081
      command: start-dev
      depends_on:
        - mailpit
      volumes:
        - keycloak_data:/opt/keycloak/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"   # Mailpit web interface
      - "1025:1025"   # SMTP
    environment:
      - MAILPIT_API=1

volumes:
  keycloak_data:
