name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password (or token)

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./api-gateway/Dockerfile  # Correct path to Dockerfile inside api-gateway
          push: true  # Set to true to push to Docker Hub
          tags: desmondveeke/kwetter-gateway:latest  # Replace with your Docker Hub repository and tag
